id: 11461a56276242a58feb605d3291f193
initial_creation_type: ocr
source_metadata:
  volumes:
    30526b260e1944ad87d23c21552e7392:
      base_file: v026.txt
      image_group_id: I1PD95871
      title: ཆོས་ཀྱི་དབྱིངས་ལྟ་བའི་གླུ།
      total_pages: 1902
      volume_number: 26
